<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;netstandard2.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <AssemblyName>KspMp.Shared</AssemblyName>
    <RootNamespace>KspMp.Shared</RootNamespace>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../KspMp.Net.LiteNetLib/KspMp.Net.LiteNetLib.csproj" />
  </ItemGroup>
</Project>
